### ISSUE TITLE
Reports overhaul for 1.9: Redux

### ISSUE THREAD

**Issue by ramiabraham** [AffiliateWP/AffiliateWP#1525]
* [x] PR: #1596

The reports overhaul in `1.9`contains a wide variety of improvements which can be made given the new objects, meta boxes, and other functionality. This issue provides a thread to track a new, concise roadmap of the Reports _Redux_ to be implemented/refactored.

- This issue is originally tracked on thread #1076.
- The original feature branch, `issue/1076`, has been deleted and replaced with a base of `release/1.9`: https://github.com/AffiliateWP/AffiliateWP/tree/issue/1076

### Roadmap:

(These items are tentatively ordered by priority; the first focus will be tabular data).

- [x] Add new tab screens layout/order: Affiliates, Referrals, Visits, Campaigns.
- [x] Tabular data for all tab screens.
- [x] **(wip)** Add search filters for each of the tabular data views (see _Search filter notes_ below).
- [x] **(wip)** Add dynamic `filter`s for each data table, to allow for easy addition of add-on data in the future.
- [x] Extend graphs to include additional data filters, adjust for related overlays
- [x] Extend graphs to include pan and zoom functionality
- [x] Extend graphs to display the currently-rendered tabular data range and parameters in sync with the primary tabular data (uses `WP_List_Table`'s `ajax` methods to initialize data).
- [ ] Extend core exporter to allow for modular usage, 
- [ ] Extend core exporter to account for the optional range of new data available in Reports views
- [ ] Extend core exporter to use a variant of the EDD ajax exporter.
- [ ] Use core meta boxes where relevant within reports.
- [ ] Use class abstractions (eventually) for list tables. In progress in #1528.

----

## Search filter notes:

Here are some of the features / report views we'd like to achieve:

Affiliates
- [x] Affiliates registered over X timeframe
- [x] Affiliates that have sent traffic (visits) in X timeframe
- [x] just converted visits
- [x] non-converted visits
- [x] Affiliates that earned $x.xx - $x.xx in X timeframe
- [x] Affiliates that earned $x.xx in Y period over X timeframe (ex: $100 per month in 2015)
- [ ] Earnings mix of affiliates (ex. John Doe accounts for 80% of earnings)
- [ ] Affiliate earnings over X timeframe

Referrals
- [x] Best dates by performance
- [ ] Highest referred products
- [x] Highest/lowest earning affiliates
- [ ] Best conversion rates by product
- [ ] Best product categories
- [ ] A list of products sold (w/quantity) through affiliates
- [x] By affiliate name

Visits
- [x] Best / worst landing pages
- [x] Conversion rates over X timeframe
- [x] Conversion rates by affiliate
- [x] Number of visits over X timeframe

Campaigns
- [x] Best / worst converting campaigns
- [x] Best / worst campaigns by affiliate

Global filters / features for all reports:
- [x] Include/exclude affiliates
- [x] Start date
- [x] End date
- [x] Status
- [ ] All report views can be exported to a CSV

**Comment by sumobi** [comment]
Some survey feedback which relates to reporting:

> Make a super clear overview per affiliate HOW they have earned, which amount though which products, on which dates, and what is their conversation rate, overall as well as per month, etc. I want to be able to see very clear and detailed info and also being able to provide this super clear information with my affiliates in pdf summery.

**Comment by ramiabraham** [comment]
I love the idea of integration-specific data. Thoughts on survey feedback:

- My first reaction was that it could go on the _edit affiliate_ screen, but this might fit better as something that shows in Reports, as something which expands on click of a specific affiliate. Both have their downsides:
    - Adding this information to the edit affiliates screen breaks detailed Reports data out of the Reports section, which may confuse users.
    - Adding this view to the Reports area greatly increases the tasks needed, so may be better for 1.9.x? Per-product referral stats for example need to support _all_ relevant integrations. 

---

- PDF output: I think a valid argument is that this is beyond the scope AffiliateWP, and introduces an element we'll need to support (such as integrating, say, the `fPDF` or `PDFlib` libs) but one way to get around this, while still providing an alternative to the `.csv` exporter, is to provide simple _print styles_. We could then provide a button to "print" a good-looking view of the current reports UI, exposing the view to whatever output formats are desired, such as saving to PDF in-browser, etc.

**Comment by pippinsplugins** [comment]
I believe everything should be contained within the Reports page. We could always add a link to a filtered reports page from the affiliate edit screen, but the data itself should be shown in reports.

Note: we will not use a PDF library nor will we will support downloading PDF files of any kind. After doing that in EDD, several EDD extensions, and RCP, I learned the hard way that those libraries are absolutely _massive_, extremely inflexible, and overall result in bigger problems than they solve. For example, due to the massive file size, it ends up preventing a lot of people being able to upload the plugin through WordPress's upload as the zip file is larger than the max upload size.

CSV exports for the win. Lean, flexible, efficient.

**Comment by worldtravlr** [comment]
Excited about all the activity here! :-)  Keep it up @ramiabraham and awesome AffiliateWP team!  Cheers!

**Comment by ramiabraham** [comment]
Update on progress, inclusion of mockups:

- List table views now use the primary object list tables
- A campaign list table is in the process of being defined, and is located in `admin/campaigns/`.

----

### Search filters

Reports list table appearance with search filters:

![Reports overview](http://i.imgur.com/g14jR1D.png "Overview")

The search filters contain the following operators:

- greater than
- less than
- greater than or equal to
- less than or equal to
- equals

The search can then be narrowed by the search term input field, as well as the date parameters:

![filter operators](http://i.imgur.com/dxd7kAc.png "Operators")
![filter operators](http://i.imgur.com/XwWoUqw.png "Operators")

----

### TODO:

- Complete appearance (minor css, improve UI 
- Complete js needed to adjust logic chain for each operator type (for example, preventing cases where you could create a non-sensical statement such as "Show `status` _greater than_ `5`")
- Complete related queries for each search filter operator type within each class' `object_data` method.

----

### Questions:

- Keep or nix the meta boxes?
- Graphs are taking up some notable real estate. A sub-tabbed UI? Remove graphs?
- If removing graphs form individual tabs, should they be consolidated into one main reports overview tab?
- Another option would be to place the list table itself, as well as any other sections shown in a tab, into their own meta boxes, allowing the user to place things wherever they like.

----

After search filters are completed, I plan on moving to extending the base `AffWP_Exporter` class, for use in these list tables.

**Comment by pippinsplugins** [comment]
That's looks great.

>>>Keep or nix the meta boxes?

The overview meta boxes? Let's leave them untouched for now, at least until we figure out the exact answers to some of my questions below.

>>>Graphs are taking up some notable real estate. A sub-tabbed UI? Remove graphs?

I would prefer that the graphs stay but that they be a direct representation of the data presented in the list tables.

>>>Another option would be to place the list table itself, as well as any other sections shown in a tab, into their own meta boxes, allowing the user to place things wherever they like.

Possibly but let's get the data itself all displayed before we're that concerned with exactly where it's shown (in or out of a meta box).

Now a few more questions.

1. Does the graph show the same data as is in the table, per the chosen filters? If the graphs stay, they'll need to accurately represent the tabular data shown.

2. What data is intended to be shown in each list table (the ones currently below the graphs) that is different from the main object list tables? For example, the screenshot above shows the same data as the primary `Affiliates > Referrals` table. In order for it to make sense that the filters / graph / list table be separate from the main Referrals list table, it needs to show very different data, otherwise we might as well just combine reports with each of the existing list tables.

Additional comments:

1. Please do not work on export until display of data is 100% functional. Export should be one of the last items attacked.

2. The current filters are excellent, but we don't yet have "Report" filters. Display all referrals that are greater than X is nice and all, but not really that useful. What a site admin really needs to see, for example, is a summed total of earnings between Date A and Date B, or a list of the affiliate accounts that have earned X in time period Y, or perhaps a list of affiliate accounts with a conversion rate above 2%.

Refer back to the `Search filter notes` posted above for further examples: https://github.com/AffiliateWP/AffiliateWP/issues/1525#issue-170031308

Those are the kinds of "reports" we need much more so than a few drop downs that simply filter the existing views.

**Comment by michaelbeil** [comment]
**Keep or nix the meta boxes?**

On the Overview screen?

**Graphs are taking up some notable real estate. A sub-tabbed UI? Remove graphs?
If removing graphs form individual tabs, should they be consolidated into one main reports overview tab?**

I like the look of the graphs. 

**Another option would be to place the list table itself, as well as any other sections shown in a tab, into their own meta boxes, allowing the user to place things wherever they like.**

Could be interesting. I would want to do some user testing on the current iteration prior to any movement on this.

**Comment by pippinsplugins** [comment]
Would it be helpful @ramiabraham if I put together some sketches to better show what those reports might look like?

**Comment by ramiabraham** [comment]
Yes x 100000 :)

**Comment by ramiabraham** [comment]
@michaelbeil @pippinsplugins (Note on the meta boxes: I meant the meta boxes which show on the individual tabs within Reports)

**Comment by michaelbeil** [comment]
Oh, gotcha. If they seem to line up with Pip's mockup then yes :smile:.

**Comment by ramiabraham** [comment]
@pippinsplugins 

This is a mockup of the noted repeater UI idea, which would display above the list table. This would provide a means to create complex queries, and would immediately be familiar to those using plugins such as Gravity Forms, ACF, or CMB2.

![repeater mockup](http://i.imgur.com/AoCEduc.gif "repeater")

The UI would adjust slightly, depending on what's selected, such as the date changing the available filter options to date-based choices:

![date mockup](http://i.imgur.com/F9wGGj5.png "date")

![date mockup](http://i.imgur.com/cQIfqEy.png "date")

----

Notes: 
- A submit button would be added in the bottom-right of the meta box
- An easy to find general search box would still be present in the usual location, at the top right of the screen above the list table, adjacent to the search filters meta box.
- Because a meta box is collapsible, it may make the graphs being present less annoying to some

**Comment by michaelbeil** [comment]
There could be a lot of potential with this type of filtering. As long as the list table is updated with the graph and the appropriate data is displayed, this seems like a winner. 

`and` as well as an `or` options might be very helpful for further granular control.

**Comment by worldtravlr** [comment]
These filters look awesome!  Would some/all of them be available on the front end for affiliates as well to filter their results?

For the graphs, can you add maybe 50 referrals on the same day as that will better show my issue with the current graphs.  If there is one a sale a day, the graphs are helpful, if there or a lot, then they become useless unless they change from showing each refer to showing a daily total.

This can be seen for example here - https://cloud.githubusercontent.com/assets/6686642/14872690/c039ff9c-0d29-11e6-8dae-9594d41033d8.jpg

**Comment by ramiabraham** [comment]
@worldtravlr We're still in the early stages of this particular feature, but I'll be updating here daily (or near daily) as things progress. 

However I think it's safe to say this will be focusing entirely on the admin Reports interface. (Features for the affiliate area would be tracked separately).

Thanks for noting the graphs issue - I do recall this from #1076, and definitely plan on re-adding the pan/zoom functionality that was present in the first iteration.

**Comment by sumobi** [comment]
Love the repeater field WIP, this could actually be handy for some other add-ons in the works... (hint hint). I agree with everything said so far, that's all I have for now :(

**Comment by wordmaid** [comment]
Phew! I can see a huge amount of work has gone into this so far, and there will likely be more. This is _so_ exciting! 🙌 I agree with the direction and all looking good. As I get more involved in the affiliate management I might pick up a few more things to add in the future. 

There is one major feature missing for me, which is absolutely relevant for Reporting...

**Showing the total revenue earned via affiliate-generated sales**:  https://github.com/AffiliateWP/AffiliateWP/issues/492


To avoid any confusion, here's what I mean by an "affiliate-generated sale":
1. Affiliate refers customer to site, and has a 20% referral rate
2. Customer purchases product(s) total = $200
3. Affiliate receives referral amount = $40
4. The affiliate-generated sale amount is the total, minus the referral amount: $200 - $40 = $160

Showing a customer their store's total revenue generated from affiliate-generated sales will bring so much more value to AffiliateWP. If they can easily see that $3,000 of the $10,000 they earned in a year came from affiliate sales, there will be no question regarding the value of affiliate marketing (and in turn, AffiliateWP). We'll make more sales, and we'll retain more loyal customers.

Since we are looking at including things like the below in reporting:
- Highest referred products
- Best conversion rates by product
- Best product categories
- A list of products sold (w/quantity) through affiliates
... could we also tap into the total revenue generated from these affiliate-generated sales?

There was a question in our recent survey which was "Have you earned more in affiliate-referred sales than what you paid for your AffiliateWP license?". The majority of people answered "No" or "I'm not sure" because they probably aren't sure how to work it out. Plus, we've had multiple support tickets in the past asking where this information can be found. 

I think we should absolutely provide customers with this data within AffiliateWP, as it will allow them to see how well their sales are doing based on their affiliates' efforts. Then they can bust out percentages that _mean something_ to their business and their forecasting (i.e. 30% of all revenue ($ profit), 10% of all sales (number of sales), etc.).

I imagine customers might want to see:
- Total $ amount of affiliate-generated revenue (_excluding_ referral amounts) - this is probably the most important information
- Total $ amount of affiliate-generated revenue (_including_ referral amounts)
- Total $ amount of affiliate referrals - separate, but alongside the total revenue - so customers can see how much they have paid to affiliates
- Total number of affiliate-generated sales.

Plus, it would be amazing to include:
- Percentages for the above outputted figures, so customers can quickly see how their affiliate sales are performing
- The ability to filter the above data by time period.

I hope the above makes sense - let me know if anything is unclear or if I can explain better. 😛

**Comment by sumobi** [comment]
^ Ahh yes, this is something I have been wanting to see for quite some time. I absolutely agree we should have this, if not for 1.9, for a point release (though technically https://github.com/AffiliateWP/AffiliateWP/issues/492 is slated for 1.9). 

It does need to be filterable so can't go on a screen that isn't. Where? Not sure yet.

**Comment by sumobi** [comment]
What about a "sales" tab?

**Comment by wordmaid** [comment]
😱 YES!

**Comment by michaelbeil** [comment]
Yes to a sales tab ... please?! I totally forgot about affiliate-generated sales and how useful that would be as we have discussed this in the past.

**Comment by ramiabraham** [comment]
Thanks everyone for the _excellent_ feedback here. 

- Presently, I'm continuing with getting the primary search filters defined. Right now, I'm working on logic chains for each operator. 

The search filters and related data displays are the primary focus, so after that's pushed/tested etc, we could:

- Implement some limited queries _only_ for the above-noted sales data, and display in two or three meta boxes on a new `Sales` tab within the `Reports` tab, or on the primary `Affiliates` &rarr; `Overview` screen.

----
In the longer-term, accurately determining the order total for orders in which a referral was generated has a long list of caveats which must be accounted for:

- We do not store the order total for any transaction (or any other data, aside from the `context` and `reference`. This means that we have some options:
    - **The good** Introduce a new field into the `referral` object, which contains the order total, saving us the additional query to the integration used for the order which generated the referral.
    - **The bad** Use a broader approach, with `affwp_get_affiliate_earnings()`. We could loop through all affiliates periodically, cache the value, and count the total.
    - **The ugly** Directly query the integration's `order` when calculating data, using the `Reference` as the integrations' `order ID`.
    - 
- All add-ons and core functionality which can modify a referral rate will need to be considered, including tiered rates and coupons.

Directly querying order totals by using the `Reference` field is of course not an option, and looping through all affiliate earnings to get a grand total isn't a _big_ deal performance-wise (since we'd implement as a background process (or other performant process, such as a step-batch process).

I think a good place to start, once this portion is in progress, may be a reduced-case implementation of the affwp_get_affiliate_earnings() loop:

- Use the already-defined core methods to calculate. Core already determines the referral rate of a referral, and accounts for various cases (checks for add-ons, product rates, affiliate-specific rates, etc). Once this rate is determined, we can find the order total using something like:

`$maybe_order_total = $referral->amount / ( $referral->rate / 100 )`

Looking forward to checking this out again with fresh eyes once search filters are 💯 though.

**Comment by pippinsplugins** [comment]
We should probably consider adding a new column to the referrals table for `order_total` to make these reports easier. Could also include an upgrade routine to update all referral records or backfill them on demand.

**Comment by ramiabraham** [comment]
Order total added with tentative `2.0` milestone ( #1547 ).

**Comment by ramiabraham** [comment]
Status update!

- Search filters are getting closer. Will be working on them more over the next couple days. 
- The completed filters are noted above ([comment link](https://github.com/AffiliateWP/AffiliateWP/issues/1525#issue-170031308))

- So far, the filters I've focused on building are those that can be determined with AffiliateWP data _only_. As I prepare to move to Referrals-specific filters, though, these noted searches stand out:
    - Highest referred products
    - Highest/lowest earning affiliates
    - Best conversion rates by product
    - Best product categories
    - A list of products sold (w/quantity) through affiliates

    There's presently no way to determine this data without querying the integration directly. As discussed in [the `order_totals` feature](https://github.com/AffiliateWP/AffiliateWP/issues/1547), we'll need similar stuff to be added here. 
    My plan at the moment is to directly query the integration, using the variety of wrappers available such as `edd_get_payment_meta()` etc. Since Reports are an "on-demand" interface that won't be constantly taxing the site, I think this is ok to use. 
    Once we have the data in AffiliateWP, we can cache with a filterable lifetime of course etc.

    _*ETA on next push is this evening or tomorrow...depending on how heavy some of these queries turn out to be._

**Comment by pippinsplugins** [comment]
@DrewAPicture the `Affiliates` tab isn't quite working. The `Top Earning` and `Highest Converting Affiliates` boxes are acting very irregularly. Go to the live site to see examples of this: https://affiliatewp.com/wp-admin/admin.php?page=affiliate-wp-reports&tab=affiliates&range=last_month

Hint: our top earning affiliate starts with W (ID 68).

**Comment by worldtravlr** [comment]
New charts and reporting are awesome by the way!  Thanks so much @ramiabraham and team!
