### ISSUE TITLE
Introduce a generic, Ajax-based batch processor

### ISSUE THREAD

**Issue by DrewAPicture** [AffiliateWP/AffiliateWP#1707]
Scope in progress. Right now, we have a bunch of export and migration scripts that all rely on server-side step processing. Realistically, abstracting the processing step to a generic batch system has a lot of benefits in terms of efficiency, performance, and UX.

And for this glorious work, we get the opportunity to reuse the aforementioned batch processor for other potential intensive tasks like database upgrades, importers (!), etc.

**Comment by michaelbeil** [comment]
Related: https://github.com/AffiliateWP/AffiliateWP/issues/1311

**Comment by DrewAPicture** [comment]
@AffiliateWP/core:

### Current Batch Processor Status:

**Batch processing is implemented pretty simply:**
- Core processes are "registered" via a `Registry` class, which builds a map of `batch_id => class` pairs used by the generic Ajax callback.
- Third-parties can also "register" batch processes in much the same way, but on a `affwp_batch_process_init` action.
- Batch processes implement one or more interfaces to enforce the architectural contract rather than extending an abstract class. The interfaces are there for self-documentation more than anything: `AffWP\Utils\Batch_Process\Base` and/or `With_PreFetch`
- All processes are tied to a single, generic Ajax callback, `affwp_process_batch_request`, which is triggered by setting the `affwp-batch-form` class and two data attributes (`data-batch_id` and `data-nonce` in the `<form>` tag in the UI. These attributes tie the existing forms to the new batch processing JS API.

As of this writing, user migration has been implemented as a batch process by adjusting the `<form>` tag in tools.php and registering the `AffWP\Utils\Batch_Process\Migrate_Users` class under the `migrate-users` batch ID in the `Registry` class.

`Migrate_Users` was the test case. Now that it's implemented and as expected (with a couple of rough edges), implementing for the other scripts should be pretty fast and straightforward.

**Related functionality and initialization:**
- Introduces `AffWP\Utils\Data_Storage` class for use throughout AffWP core, but specifically for use by batch processors implementing the `With_PreFetch` interface. Accessed via `affiliate_wp()->utils->data`
- Introduces `Affiliate_WP_Utilities` class, initialized at the top level under `$utils`
- `Affiliate_WP_Utilities` Initializes the batch process registry under `$batch` and the `Data_Storage` class under `$data`
- Deprecates data storage methods in `Affiliate_WP_Migrate_Base` in favor of leveraging `Data_Storage` methods externally

### Other Things in this PR:

- Introduces `Base` and `CSV` interfaces to enforce architectural contracts for exporters (base classes are not abstract)
- Introduces `Base` interface to enforce contract for importers
- Moves settings import to its own class, implementing the `Importer\Base` interface
- Moves settings export to its own class, implementing the `Exporter/CSV` interface
- Moves logging methods to the top-level `Affiliate_WP_Migrate_Base` class for use by all migration scripts

### Roadmap:

* [x] Create a generic Ajax callback for initiating a single step in the batch process
* [x] Write JS handler(s) capable of tying to a minimum number of attributes implemented in existing UI
* [x] Handle temporary data storage for passing data around between instances during each step
* [x] Create a batch process registry for registering and retrieving data about individual batch processes
* [x] Handle the instantiation and initialization chain from the top-level down
* [ ] Standardize "done message" handling, i.e. displaying the "done" message in the notice div
* [x] Implement batch processing for "User Accounts" (migrate users)
* [ ] Implement batch processing for WP Affiliate migration script
* [ ] Implement batch processing for Affiliates Pro migration script
* [ ] Implement batch processing for Export Affiliates script
* [ ] Implement batch processing for Export Referrals script
* [ ] Implement batch processing for Export Referral Payouts script
* [ ] Write dev docs for implementing a batch process
* [ ] Write tests for `Data_Storage`
* [ ] Write tests for the Ajax callback (if not too convoluted)
* [ ] Write tests for `Registry`

**Comment by pippinsplugins** [comment]
Fantastic @DrewAPicture. Let me know if you'd like anything specific tested while the roadmap is worked on.

**Comment by DrewAPicture** [comment]
Thursday progress aiming toward a Friday deadline:

* Added a generic handler for triggering export downloads
* Hooked up `Export_Affiliates` to the download mechanism
* Introduced `Export_Referrals` with full parameter and download capability

**Comment by DrewAPicture** [comment]
@AffiliateWP/core this is ready for review.

**Comment by pippinsplugins** [comment]
Woot! I'll begin testing tomorrow!

**Comment by pippinsplugins** [comment]
@DrewAPicture starting to test this out.

I did notice one small layout issue with the spinner:
![screen shot 2017-01-02 at 4 20 13 pm](https://cloud.githubusercontent.com/assets/1034109/21596889/661bf7f2-d107-11e6-9487-e7a808d18963.png)

**Comment by pippinsplugins** [comment]
@DrewAPicture the `Status` dropdown in the affiliate export doesn't work. It always exports affiliates of all statuses.

**Comment by DrewAPicture** [comment]
@pippinsplugins I've fixed the issue with arbitrary fields binding to form submissions. And after some tinkering with the CSS on the spinner, I've instead opted to append it to the submit button wherever that might occur in the layout rather than trying to work around our homegrown progress bar solution.

Looks like this:

![New spinner location](https://cl.ly/3d283R0o3S3r/Screen%20Shot%202017-01-03%20at%2012.19.45%20PM.png)

**Comment by pippinsplugins** [comment]
@DrewAPicture This looks a bit weird to me:
![screen shot 2017-01-03 at 8 37 12 pm](https://cloud.githubusercontent.com/assets/1034109/21630176/76bc37fa-d1f4-11e6-8124-b5735bcc0455.png)

Possible to have the layout we had before in terms of the display and positioning of the progress bar?

I'm good with the position of the spinner now.

**Comment by DrewAPicture** [comment]
@pippinsplugins You screenshot didn't come through, but I think I saw what you were referring to. 741605b should improve the display of the progress bar.

**Comment by DrewAPicture** [comment]
Current display:

![Progress bar](https://cl.ly/2g0o412X1h28/Screen%20Shot%202017-01-03%20at%2010.07.28%20PM.png)

![Success notice](https://cl.ly/451W3b03291s/Screen%20Shot%202017-01-03%20at%2010.08.19%20PM.png)

**Comment by pippinsplugins** [comment]
@DrewAPicture Perfect, that's what I was looking for!

**Comment by pippinsplugins** [comment]
Works great now.

@DrewAPicture anything left on your todo list before merge?

**Comment by DrewAPicture** [comment]
@pippinsplugins Yes, tests, but since progress on other issues depends on this I'm fine merging the PR and keeping this issue open to finish the tests.

**Comment by DrewAPicture** [comment]
Batch Processing has been merged 🎉

**Comment by pippinsplugins** [comment]
🎉

**Comment by pippinsplugins** [comment]
@DrewAPicture Two things I just found while testing #1046:

1. Clicking "cancel" on the browser alert doesn't actually cancel. The batch process still starts.
2. If no results are found for the requested parameter, we should change the message. Right now it says `A payout log for 0 affiliates was successfully generated.`. If it's `0` we should change it to something like `No {x} were found.`

**Comment by DrewAPicture** [comment]
1. Clicking "cancel" in the `confirm()` dialog should now work as of accc80e0b4b4e4a1883c9f9d051bbc4979f328c4

2. I've adjusted the message to "No unpaid referrals were found matching your criteria." Done in a5049189ffef71510d18133618ae9c628c2c49a3

**Comment by pippinsplugins** [comment]
1. Works!

2. Works!

**Comment by pippinsplugins** [comment]
Could we adjust the spacing on the progress bar please?
![screen shot 2017-01-07 at 10 23 34 pm](https://cloud.githubusercontent.com/assets/1034109/21747293/0362b11c-d528-11e6-9c6b-9bedca092c55.png)

**Comment by DrewAPicture** [comment]
@pippinsplugins I've adjusted the CSS. How's this?

![Progress bar padding](https://cl.ly/3D2w1V3F2a2w/Screen%20Shot%202017-01-08%20at%208.38.59%20AM.png)

**Comment by DrewAPicture** [comment]
Added tests for the `Registry` class.

**Comment by DrewAPicture** [comment]
Added tests for the `Registry` class in a new PR: #1898.

**Comment by DrewAPicture** [comment]
Also added tests for `Data_Storage`.

**Comment by pippinsplugins** [comment]
Looking good here!

**Comment by pippinsplugins** [comment]
I believe this is ready for merge!

**Comment by DrewAPicture** [comment]
Tests merged in #1898. Closing :)

**Comment by pippinsplugins** [comment]
❤🍺

**Comment by pippinsplugins** [comment]
We have a couple of display issues with this still so re-opening.
![screen shot 2017-01-17 at 12 57 17 pm](https://cloud.githubusercontent.com/assets/1034109/22035169/8f1c0864-dcb4-11e6-8a18-fc78bd906b40.png)
![screen shot 2017-01-17 at 12 57 55 pm](https://cloud.githubusercontent.com/assets/1034109/22035181/9a7c6230-dcb4-11e6-80af-b0a64c437413.png)

Notice the bottom overlap and how the progress bar is sitting outside of the box.

**Comment by DrewAPicture** [comment]
@pippinsplugins Browser and version?

**Comment by pippinsplugins** [comment]
@DrewAPicture Chrome Version 55.0.2883.95 (64-bit)

**Comment by pippinsplugins** [comment]
Oops, forgot to reopen.

**Comment by DrewAPicture** [comment]
Added a PR that addresses the display issues: #1948 

Upgrade notice looks like this now:

![Upgrade notice](https://cl.ly/0H2v2a3w2g30/Screen%20Shot%202017-01-23%20at%202.58.23%20PM.png)

Generated markup for a standard batch process looks like this:

![Standard process](https://cl.ly/0i0W0C1i3Q39/Screen%20Shot%202017-01-23%20at%202.59.48%20PM.png)

**Comment by pippinsplugins** [comment]
Merged!
